name = "aiken-lang/stdlib"
version = "1.7.0"
description = "The Aiken Standard Library"

[repository]
user = "aiken-lang"
project = "stdlib"
platform = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "main"
source = "github"
